export enum Job {
	PLD_FFXIV = 'Paladin_FFXIV',
	WAR_FFXIV = 'Warrior_FFXIV',
	DRK_FFXIV = 'Dark Knight_FFXIV',
	GNB_FFXIV = 'Gunbreaker_FFXIV',
	WHM_FFXIV = 'White Mage_FFXIV',
	SCH_FFXIV = 'Scholar_FFXIV',
	AST_FFXIV = 'Astrologian_FFXIV',
	SGE_FFXIV = 'Sage_FFXIV',
	MNK_FFXIV = 'Monk_FFXIV',
	DRG_FFXIV = 'Dragoon_FFXIV',
	NIN_FFXIV = 'Ninja_FFXIV',
	SAM_FFXIV = 'Samurai_FFXIV',
	RPR_FFXIV = 'Reaper_FFXIV',
	BRD_FFXIV = 'Bard_FFXIV',
	MCH_FFXIV = 'Machinist_FFXIV',
	DNC_FFXIV = 'Dancer_FFXIV',
	BLM_FFXIV = 'Black Mage_FFXIV',
	SMN_FFXIV = 'Summoner_FFXIV',
	RDM_FFXIV = 'Red Mage_FFXIV',
	BLU_FFXIV = 'Blue Mage_FFXIV',
}

export enum Class {
	GLA_FFXIV = 'Gladiator_FFXIV',
	MRD_FFXIV = 'Marauder_FFXIV',
	ACN_FFXIV = 'Arcanist_FFXIV',
	PGL_FFXIV = 'Pugilist_FFXIV',
	LNC_FFXIV = 'Lancer_FFXIV',
	ROG_FFXIV = 'Rogue_FFXIV',
	ARC_FFXIV = 'Archer_FFXIV',
	THM_FFXIV = 'Thaumaturge_FFXIV',
	CNJ_FFXIV = 'Conjurer_FFXIV',
}

export enum Role {
	TNK_FFXIV = 'Tank_FFXIV',
	HLR_FFXIV = 'Healer_FFXIV',
	M_DPS_FFXIV = 'Melee DPS_FFXIV',
	PR_DPS_FFXIV = 'Physical Ranged DPS_FFXIV',
	MR_DPS_FFXIV = 'Magical Ranged DPS_FFXIV',
}

export const associations: Record<Job | Class | 'Role', [] | [Role] | [Role, Class]> = {
	[Job.PLD_FFXIV]: [Role.TNK_FFXIV, Class.GLA_FFXIV],
	[Job.WAR_FFXIV]: [Role.TNK_FFXIV, Class.MRD_FFXIV],
	[Job.DRK_FFXIV]: [Role.TNK_FFXIV],
	[Job.GNB_FFXIV]: [Role.TNK_FFXIV],
	[Job.WHM_FFXIV]: [Role.HLR_FFXIV, Class.CNJ_FFXIV],
	[Job.SCH_FFXIV]: [Role.HLR_FFXIV, Class.ACN_FFXIV],
	[Job.AST_FFXIV]: [Role.HLR_FFXIV],
	[Job.SGE_FFXIV]: [Role.HLR_FFXIV],
	[Job.MNK_FFXIV]: [Role.M_DPS_FFXIV, Class.PGL_FFXIV],
	[Job.DRG_FFXIV]: [Role.M_DPS_FFXIV, Class.LNC_FFXIV],
	[Job.NIN_FFXIV]: [Role.M_DPS_FFXIV, Class.ROG_FFXIV],
	[Job.SAM_FFXIV]: [Role.M_DPS_FFXIV],
	[Job.RPR_FFXIV]: [Role.M_DPS_FFXIV],
	[Job.BRD_FFXIV]: [Role.PR_DPS_FFXIV, Class.ARC_FFXIV],
	[Job.MCH_FFXIV]: [Role.PR_DPS_FFXIV],
	[Job.DNC_FFXIV]: [Role.PR_DPS_FFXIV],
	[Job.BLM_FFXIV]: [Role.MR_DPS_FFXIV, Class.THM_FFXIV],
	[Job.SMN_FFXIV]: [Role.MR_DPS_FFXIV, Class.ACN_FFXIV],
	[Job.RDM_FFXIV]: [Role.MR_DPS_FFXIV],
	[Job.BLU_FFXIV]: [Role.MR_DPS_FFXIV],
	[Class.GLA_FFXIV]: [Role.TNK_FFXIV],
	[Class.MRD_FFXIV]: [Role.TNK_FFXIV],
	[Class.ACN_FFXIV]: [Role.HLR_FFXIV],
	[Class.PGL_FFXIV]: [Role.M_DPS_FFXIV],
	[Class.LNC_FFXIV]: [Role.M_DPS_FFXIV],
	[Class.ROG_FFXIV]: [Role.M_DPS_FFXIV],
	[Class.ARC_FFXIV]: [Role.PR_DPS_FFXIV],
	[Class.THM_FFXIV]: [Role.MR_DPS_FFXIV],
	[Class.CNJ_FFXIV]: [Role.HLR_FFXIV],
	Role: [],
}

export type Classification = Job | Class | Role[];
