import { Job } from '../../classification';
import { ActionType, Pos, defineActions } from '../../Action';

const names = [
	'Jump',
	'Elusive Jump',
	'Doom Spike',
	'Spineshatter Dive',
	'Chaos Thrust',
	'Dragonfire Dive',
	'Battle Litany',
	'Fang and Claw',
	'Wheeling Thrust',
	'Geirskogul',
	'Sonic Thrust',
	'Dragon Sight',
	'Mirage Dive',
	'Nastrond',
	'Coerthan Torment',
	'High Jump',
	'Raiden Thrust',
	'Stardiver',
	'Draconian Fury',
	"Heavens' Thrust",
	'Chaotic Spring',
	'Wyrmwind Thrust',
] as const;
export type DRGActionName = (typeof names)[number];

export const DRGActions = defineActions(
	Job.DRG_FFXIV,
	({
		activateEffect,
		deactivateEffect,
		effectIsActive,
		adjustActionProperty,
	}) => [
		{
			name: 'Jump',
			level: 30,
			type: ActionType.ABILITY,
			potency: 250,
			recast: 30,
			range: 20,
			onUse: () => activateEffect('Dive Ready'),
		},
		{
			name: 'Elusive Jump',
			level: 35,
			type: ActionType.ABILITY,
			recast: 30,
			range: 0,
			onUse: () => adjustActionProperty('Elusive Jump', 'recast', 15),
		},
		{
			name: 'Doom Spike',
			level: 40,
			type: ActionType.WEAPON_SKILL,
			potency: 110,
			range: 10,
			radius: 10,
			breaksCombo: true,
			onUse: () => console.log('Doom Spike used!'),
		},
		{
			name: 'Spineshatter Dive',
			level: 45,
			type: ActionType.ABILITY,
			potency: 190,
			recast: 60,
			range: 20,
			onUse: () => console.log('Spineshatter Dive used!'),
		},
		{
			name: 'Chaos Thrust',
			level: 50,
			type: ActionType.WEAPON_SKILL,
			potency: 100,
			comboPotency: 220,
			positionalBonus: [Pos.REAR, 40] as [Pos, number],
			breaksCombo: true,
			combos: ['Disembowel'],
			onCombo: () => {
				activateEffect('Chaos Thrust', { onTarget: true });
				activateEffect('Wheel in Motion');
			},
		},
		{
			name: 'Dragonfire Dive',
			level: 50,
			type: ActionType.ABILITY,
			potency: 300,
			recast: 120,
			range: 20,
			radius: 5,
			onUse: () => console.log('Dragonfire Dive used!'),
		},
		{
			name: 'Battle Litany',
			level: 52,
			type: ActionType.ABILITY,
			recast: 120,
			range: 0,
			radius: 30,
			onUse: () => console.log('Battle Litany used!'),
		},
		{
			name: 'Fang and Claw',
			level: 56,
			type: ActionType.WEAPON_SKILL,
			potency: 260,
			positionalBonus: [Pos.FLANK, 40] as [Pos, number],
			breaksCombo: true,
			condition: () => effectIsActive('Fang and Claw Bared'),
			onUse: () => console.log('Fang and Claw used!'),
		},
		{
			name: 'Wheeling Thrust',
			level: 58,
			type: ActionType.WEAPON_SKILL,
			potency: 260,
			positionalBonus: [Pos.REAR, 40] as [Pos, number],
			breaksCombo: true,
			condition: () => effectIsActive('Wheel in Motion'),
			onUse: () => console.log('Wheeling Thrust used!'),
		},
		{
			name: 'Geirskogul',
			level: 60,
			type: ActionType.ABILITY,
			potency: 260,
			recast: 30,
			range: 15,
			charges: 3,
			radius: 15,
			onUse: () => console.log('Geirskogul used!'),
		},
		{
			name: 'Sonic Thrust',
			level: 62,
			type: ActionType.WEAPON_SKILL,
			potency: 100,
			comboPotency: 120,
			breaksCombo: true,
			combos: ['Doom Spike', 'Draconian Fury'],
			range: 10,
			radius: 10,
			onUse: () => console.log('Sonic Thrust used!'),
		},
		{
			name: 'Dragon Sight',
			level: 66,
			type: ActionType.ABILITY,
			recast: 120,
			range: 30,
			onUse: () => console.log('Dragon Sight used!'),
		},
		{
			name: 'Mirage Dive',
			level: 68,
			type: ActionType.ABILITY,
			potency: 200,
			recast: 1,
			range: 20,
			resourceGains: {
				gauge: 1,
			},
			condition: () => effectIsActive('Dive Ready'),
			onUse: () => deactivateEffect('Dive Ready'),
		},
		{
			name: 'Nastrond',
			level: 70,
			type: ActionType.ABILITY,
			potency: 360,
			recast: 10,
			range: 15,
			radius: 15,
			condition: () => effectIsActive('Life of the Dragon'),
			onUse: () => console.log('Nastrond used!'),
		},
		{
			name: 'Coerthan Torment',
			level: 72,
			type: ActionType.WEAPON_SKILL,
			potency: 100,
			comboPotency: 150,
			breaksCombo: true,
			combos: ['Sonic Thrust'],
			range: 10,
			radius: 10,
			onUse: () => console.log('Coerthan Torment used!'),
		},
		{
			name: 'High Jump',
			level: 74,
			type: ActionType.ABILITY,
			potency: 400,
			recast: 3,
			charges: 3,
			range: 20,
			onUse: () => activateEffect('Dive Ready'),
		},
		{
			name: 'Raiden Thrust',
			level: 76,
			type: ActionType.WEAPON_SKILL,
			potency: 280,
			breaksCombo: true,
			onUse: () => console.log('Raiden Thrust used!'),
		},
		{
			name: 'Stardiver',
			level: 80,
			type: ActionType.ABILITY,
			potency: 620,
			recast: 30,
			range: 20,
			radius: 5,
			onUse: () => console.log('Stardiver used!'),
			condition: () => effectIsActive('Life of the Dragon'),
		},
		{
			name: 'Draconian Fury',
			level: 82,
			type: ActionType.WEAPON_SKILL,
			potency: 130,
			breaksCombo: true, //! maybe
			range: 10,
			radius: 10,
			onUse: () => console.log('Draconian Fury used!'),
		},
		{
			name: "Heavens' Thrust",
			level: 86,
			type: ActionType.WEAPON_SKILL,
			potency: 100,
			comboPotency: 480,
			breaksCombo: true, //! maybe
			combos: ['Vorpal Thrust'],
			onCombo: () => activateEffect('Fang and Claw Bared'),
			onUse: () => console.log("Heavens' Thrust used!"),
		},
		{
			name: 'Chaotic Spring',
			level: 86,
			type: ActionType.WEAPON_SKILL,
			potency: 100,
			comboPotency: 260,
			positionalBonus: [Pos.REAR, 40] as [Pos, number],
			breaksCombo: true, //! maybe
			combos: ['Disembowel'],
			onCombo: () => {
				activateEffect('Wheel in Motion');
				activateEffect('Chaotic Spring', { onTarget: true });
			},
			onUse: () => console.log('Chaotic Spring used!'),
		},
		{
			name: 'Wyrmwind Thrust',
			level: 90,
			type: ActionType.ABILITY,
			potency: 420,
			recast: 10,
			range: 15,
			radius: 15,
			onUse: () => console.log('Wyrmwind Thrust used!'),
		},
	]
);
